### ISSUE TITLE
Seach for program: no such file or directory, global

### ISSUE THREAD

**Issue by weijietong** [tuhdo/emacs-c-ide-demo#10]
HI : 
I got the same error as the title show.My helm-gtags-find-tag does not work . The global is in the PATH . I don't know how to solve it. Wait for your answer .

**Comment by tuhdo** [comment]
Did you create tags with `helm-gtags-create-tags`?

**Comment by weijietong** [comment]
I have used gtags to create the tags.In the root directory ,it already has the GTAGS、GRTAGS、GPATH directories there. When I use the helm-gtags-create-tags as your advice,it shows :Searching for program:no such file or directory,gtags.

**Comment by weijietong** [comment]
I solved it by setting the exec-path,before I only set the "PATH".But it seems that the helm-gtags-find-tag does not work as expect,while other helm-gtags work well.

**Comment by weijietong** [comment]
tks for your answer
