### ISSUE TITLE
files out of sync with repo tudo.github.io/c-ide.html

### ISSUE THREAD

**Issue by Boruch-Baum** [tuhdo/emacs-c-ide-demo#12]
I'm going through the c-ide.html page of your emacs tutorial repo, including using this demo repo to which is supposed to be keyed. The html page says that this repo (emacs-c-ide-demo) should perform everything that is manually listed later on that html page. However, that is quickly evidently not the case.

Already in the first section, Source Code Navigation, its apparent that at some point that the files setup-helm.el and setup-ggtags.el fell out of sync with the code snippet on the html page.

I could do the copy/paste and make a pull request if you haven't the time. An alternative would be to change the text on the c-ide.html page which currently says that by using this repository "you can ignore all the Elisp code for setting up throughout the guide", but I think the first option would be nicer.

**Comment by tuhdo** [comment]
The code is there for individuals who want to incorporate the packages into their own Elisp setup. The demo repo is just a demo and might not reflect the basic setup code.  I think a better option is to change the setup code to point the setup instructions of each package.

Also, if you want to contribute, an easier way is to use the Org files as opposed to editing the HTML files manually.

**Comment by Boruch-Baum** [comment]
> if you want to contribute, an easier way is to use the Org files as opposed to editing the HTML files manually.

I'm game. I didn't know you were using org mode, so I didn't look beyond the html in the root folder. If your merge earlier today for the issue I posted hasn't already done so, I can port my edits from the html to the org files.

Although I have found the org files, what I can't seem to find is the elisp code for the export / publishing. Where are they? How is the export from org to html performed?

> The code is there for individuals who want to incorporate the packages into their own Elisp setup. The demo repo is just a demo and might not reflect the basic setup code. I think a better option is to change the setup code to point the setup instructions of each package.

I don't understand what you mean by anything in that paragraph. Can we have a "do-over"?

> The code is there for individuals who want to incorporate the packages into their own Elisp setup.

But it's missing all the (non-trivial) install and setup code from the demo el files.

> The demo repo is just a demo and might not reflect the basic setup code.

But the only thing the demo repo does is the basic setup code.

> ... change the setup code to point the setup instructions of each package.

I don't understand what you mean.

***

The guide says, that after installing this repo:

    ` "you can ignore all the Elisp code for setting up throughout the guide" `

but from what little I've seen so far, <u>neither</u> the .el files of the demo alone nor the code snippets of the guide alone are sufficient for operation as the guide instructs. In the initial section, "Source code navigation", there is no code in common. This means that a reader of the guide would need to be directed that its _mandatory_ to install the demo (because the guide has no instructions for installing the components), and additionally _must_ copy / paste __all__ the code snippets. IMO, the result is doubly unfortunate: 

1. It makes the demo unusable as a demo alone, since its really just a skeleton of an install script without necessary keybindings, hooks, or variable definitions.

2. It makes the guide useless as a guide alone, since it lacks the install and setup elsp code for all the components it discusses.

**Comment by tuhdo** [comment]
> I'm game. I didn't know you were using org mode, so I didn't look beyond the html in the root folder. If your merge earlier today for the issue I posted hasn't already done so, I can port my edits from the html to the org files.
> 
> Although I have found the org files, what I can't seem to find is the elisp code for the export / publishing. Where are they? How is the export from org to html performed?

I already port your changes to the Org files. The HTML files are generated with my private configuration. I will update the homepage with code soon.


> I don't understand what you mean by anything in that paragraph. Can we have a "do-over"?

It means that some people have their personal `~/.emacs.d~` (not everyone uses the demo repo but their own) and want to setup their own. The setup code is there for quick copy and paste.

> But the only thing the demo repo does is the basic setup code.

But not many people structure their own Emacs configuration that way. Many people put everything in a single `init.el` file.



> I don't understand what you mean.

What I meant is that instead of presenting my own setup code, simply put a link and pointer to a package's homepage. For example, instead of setup code for ggtags, I replace it with a link to [the config section of ggtags](https://github.com/leoliu/ggtags#config). 

> but from what little I've seen so far, neither the .el files of the demo alone nor the code snippets of the guide alone are sufficient for operation as the guide instructs. In the initial section, "Source code navigation", there is no code in common. This means that a reader of the guide would need to be directed that its mandatory to install the demo (because the guide has no instructions for installing the components), and additionally must copy / paste all the code snippets

The guide is written with an assumption that readers knows how to install packages on MELPA, either learning through previous guides or somewhere else. At that point, the only setup code is all they need. The setup code there for the readers to conveniently copy and paste into their `init.el`. Prior to the guide is the guide for setting up packages, as you can see here: http://tuhdo.github.io/emacs-tutor3.html. I wouldn't want to put all guides into a single page, as they serve different purposes.

**Comment by Boruch-Baum** [comment]
OK, so how's this for a plan?
1. We close this issue, since it's devolved into a discussion focusing on your other repo - tuhdo.github.io.
2. On the tuhdo.github.io, I'll propose annotations directly onto the org files.
3. You'll post the publishing / export code, so I / others can perform that operation, and check my work before making a pull request.
4. I'll post my next suggestion(s) there.

**Comment by tuhdo** [comment]
Sure. I think I should put a link to make a reader aware that the C/C++ ide expects a reader to know how to use MELPA first, otherwise refers to previous guide.
