### ISSUE TITLE
Seach for program: no such file or directory, global

### ISSUE THREAD

**Issue by chenhong805** [tuhdo/emacs-c-ide-demo#2]
Hi, I have used this emacs setup for several weeks, but do not know how to setup ggtags, every time I run helm-gtags-find-tag, "Seach for program: no such file or directory, global" pop up in minibuffer.

I do installed GNU global using brew (on MacOS), and ggtags package via MELPA.

Could you tell me how to set it up? Thanks very much.

**Comment by tuhdo** [comment]
Hi,

You must make Emacs able to see `global` executable. In your case, you must put the path to your `global` executable in your `$PATH` variable. After that, you will be able to use `ggtags` fine.

Recently I added a refactoring package for C/C++: [Semantic Refactor](https://github.com/tuhdo/semantic-refactor). You may want to check it out. See [demos](https://github.com/tuhdo/semantic-refactor/blob/master/srefactor-demos/demos.md).

Thanks for reporting the issue.

**Comment by chenhong805** [comment]
I can run *global* in my shell, which generated *GTAGS* *GPATHS* and *GRTAGS* files. So i think the executable is included in PATH, but somehow emacs cannot find it. Do you have any idea why?

**Comment by chenhong805** [comment]
It seems *gtags* work find when using command like "ggtags-find-***". But when using "helm-gtags-***", it cannot find *global* and *gtags*.

**Comment by tuhdo** [comment]
Could you run `M-x getenv` , type "PATH" and paste the output to see if `global` and `gtags` in there?

**Comment by chenhong805** [comment]
Oh, I see. They are not included. The PATH in emacs is different with that in my shell. How can I keep them consistent?

**Comment by chenhong805** [comment]
I solved the problems by setting up 'exec-path' and 'PATH' in my 'init.el' file. Thank you very much!
