### ISSUE TITLE
moo-jump-local() gives (wrong-type-argument stringp :preselect) error

### ISSUE THREAD

**Issue by KarthikNayak** [tuhdo/emacs-c-ide-demo#6]

**Comment by KarthikNayak** [comment]
Any help on this?

**Comment by tuhdo** [comment]
Sorry about this issue. I will fix it soon. In the meantime, I highly recommend you to try [Spacemacs](https://github.com/syl20bnr/spacemacs). It has all the features I introduced in my C/C++ guide and much, much more.

**Comment by KarthikNayak** [comment]
Thanks, Will check it out, but I really like your mode :+1:
